version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    groups:
      npm:
        patterns:
          - '*'
    directories:
      - "/boilerplate-cdk"
      - "/0001-cdk-force-tagging"
      - "/0002-cdk-lambda-auth-api-gw"
      - "/0003-naming-id-practices"
      - "/0004-cloudfront-logs-glue-athena"
      - "/0005-cdk-nag"
      - "/0006-cdk-lazy"
      - "/0007-cdk-cross-stack-references"
      - "/0008-cdk-aws-chatbot"
      - "/0009-cdk-lambda-error-catcher"
      - "/0010-cdk-shared-items"
    schedule:
      interval: "daily"
