name: Run tests

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  find-changes:
    name: Find changed directories
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.find-changes.outputs.matrix }}
      matrix-empty: ${{ steps.find-changes.outputs.matrix-empty }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: find-changes
        uses: cmaster11/gha/action-get-changed-dirs@main
        with:
          base-sha: ${{ github.event.pull_request.base.sha }}
          regex: '^(\d+-|boilerplate-cdk)'

  test:
    needs: find-changes
    if: needs.find-changes.outputs.matrix-empty == 'false'
    name: Run tests
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{ fromJSON(needs.find-changes.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ matrix.directory }}/package.json
      - name: Setup deps
        working-directory: ${{ matrix.directory }}
        run: npm ci
      - name: Lint
        working-directory: ${{ matrix.directory }}
        run: npm run lint
      - name: Test
        working-directory: ${{ matrix.directory }}
        run: npm run test:ci